### ISSUE TITLE
Forge 1.0.0 file - incorrect loader version range

### ISSUE THREAD

**Issue by nanonestor** [TropheusJ/block_limit_fix#1]
Hi - tried out the "block_limit_fix-1.0.0-forge.jar" using a Forge 1.19.3 profile.

Inside mods.toml the loaderVersion range is incorrect if you want to include 1.19.3.  Forge's number for 1.19.3 is 44.x.x.
Also - does this mod work / is needed for minecraft older than 1.16.5 which the file is tagged in curseforge down to?  Unclear from  the project page description.  If not either case perhaps it would be best to add a lower limit restriction in the loaderVersion also.

Currently is loaderVersion = "(,43]"  which is any Forge version equal to or older than 1.19.2.

It should instead be loaderVersion = "(,44]"

**Comment by TropheusJ** [comment]
Thanks for letting me know. There’s a lot of versions to test, so I didn’t test every single one. 

I don’t know how far the bug goes, likely at least 1.13. However, forge only got mixin on 1.16, and fabric only exists on 1.14+, and nobody uses 1.13-1.15, so supporting older than 1.16 is unreasonable.

**Comment by nanonestor** [comment]
Sure just thought I would ask since it wasn't addressed.
